name: CI - Validaci贸n de C贸digo

# Evento que desencadena el workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del c贸digo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Step 3: Instalar dependencias
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask

      # Step 4: Iniciar el servidor en segundo plano
      - name: Start Server
        run: |
          python app.py &
          sleep 3  # Esperar a que el servidor se inicie

      # Step 5: Ejecutar prueba de verificaci贸n
      - name: Run Basic Test
        run: |
          curl http://127.0.0.1:5000 | grep "Hola Mundo"